version: '3.2'

services:

  harvester-worker:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
    command: celery -A app.tasks worker --loglevel=INFO
    environment: *env
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=polkascan
      - SUBSTRATE_RPC_URL=http://54.250.173.97:9933/
      - TYPE_REGISTRY=kusama
      - SUBSTRATE_ADDRESS_TYPE=2
    depends_on:
      - redis
      - mysql
      - substrate-node

  harvester-beat:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
      - '/usr/src/app/data'
    command: celery -A app.tasks beat --loglevel=INFO  --schedule="data/celerybeat-schedule" --pidfile="data/celerybeat.pid"
    environment: *env
    depends_on:
      - redis

  redis:
    image: redis:3.2.11
    hostname: redis

  mysql:
    image: mysql:latest
    hostname: mysql
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '33060:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polkascan
    security_opt:
      - seccomp:unconfined

volumes:
  db-data:
  substrate-data:
